Valor = input('Digite algo:')
print('O tipo primitivo desse valor é',type(Valor))
print('Só tem espaços?',Valor.isspace())
print('É um número?',Valor.isnumeric())
print('É alfabético?',Valor.isalpha())
print('É alfanumperico?',Valor.isalnum())
print('Está em maiúscula?',Valor.isupper())
print('Está em minúscula?',Valor.islower())
print('Está capitalizada?',Valor.istitle())
